name: nginx


on:
  push:
    branches: [ nginx ]


jobs:
  build_nginx:
    runs-on: ubuntu-20.04
    # if: "contains(github.event.*.message, 'subir')"
    # if: github.event.*.message === "subir"
    if: "contains(github.event.head_commit.message, '/a')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Get current date
        id: date
        run: echo ::set-output name=DATE_NOW::$(date +'%Y_%m_%dT%H_%M_%S')
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: ./
          platforms: linux/amd64
          push: true
          tags: | 
            sosan/nginx-rentacarmallorca:${{steps.date.outputs.DATE_NOW}}
            sosan/nginx-rentacarmallorca:latest

      - name: Comandos SSH Servidor
        if: "contains(github.event.head_commit.message, '/b')"
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_SERVIDOR }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY}}
          port:  ${{ secrets.PORT_SERVIDOR }}
          script: |
            cd /tmp
            mkdir certs
            echo ${{secrets.SERVER_KEY_SSL}} > ./certs/server.key && \
            echo ${{secrets.SERVER_CRT_SSL}} > ./certs/server.crt && \
            echo ${{secrets.SERVER_LOCAL_KEY_SSL}} > ./certs/server_local.key && \
            echo ${{secrets.SERVER_LOCAL_CRT_SSL}} > ./certs/server_local.crt && \
            export DOCKER_HOST=unix://$XDG_RUNTIME_DIR/docker.sock && \
            /home/alvaro/bin/docker pull sosan/nginx-rentacarmallorca:latest && \
