# https://g.codefresh.io/
# https://github.com/codefreshdemo/demochat
# https://github.com/okteto/movies/tree/master/frontend

version: "1.0"
stages:
  - "clone"
  # - "unit"
  - "build"
  - push
  # - "integration"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "sosan/Colaborador-rent-a-car-backend"
    revision: "backend"
    stage: "clone"

  # build_dev_image:
  #   title: "Building Dev image"
  #   type: "build"
  #   image_name: "sosan/Colaborador-rent-a-car-backend"
  #   working_directory: "${{clone}}"
  #   tag: "dev"
  #   dockerfile: "Dockerfile.dev"
  #   stage: "unit"

  # test:
  #   title: "Running test"
    # type: "freestyle" 
    # image: ${{build_dev_image}} 
    # working_directory: /root/colaborador-backend
    # commands:
    #   - 'npm run test'
    # stage: "unit"

  build:
    title: "Building App image"
    type: "build"
    image_name: "rent-a-car-backend"
    working_directory: "${{clone}}"
    tag: "prod"
    dockerfile: "Dockerfile"
    stage: "build"
    disable_push: true
  
  push:
    title: "Pushing 1st Docker image"
    type: push
    image_name: "sosan/rent-a-car-backend"
    tag: "latest"
    stage: "push" 
    registry: sosan
    candidate: ${{build}}

  # integration_step:
  #   type: composition
  #   stage: 'integration'
  #   composition:
  #     version: '2'
  #     services:
  #       app:
  #         image: ${{build_image}}
  #         links:
  #           - mongo
  #         ports:
  #           - 5000
  #       mongo:
  #         image: mongo
  #   composition-candidates:
  #     main:
  #       image: nhoag/curl
  #       command: bash -c "sleep 30 && curl http://app:5000/" | echo 'works'    