version: "3"

services:
  backend:
    build:
      context: "."
      dockerfile: "Dockerfile"
    container_name: contenedor-backend
    ports:
      - "3000:3000"
    volumes:
      - ./src:/home/usuarioapp/src
    restart: always
