version: "3.7"
services:
  frontend:
    restart: always
    image: sosan/frontend-rentacarmallorca:latest
    container_name: frontend
    ports:
      - 8080:8080
    environment:
      URL_BACKEND: backend
      URL_FRONTEND: frontend
      NODE_ENV: production
    secrets:
        - PORT_BACKEND
        - ENDPOINT_VARIABLES_FRONTEND
        - TOKEN_FOR_BACKEND_ACCESS
    networks:
      - gateway
    depends_on:
      - backend
  backoffice:
    restart: always
    image: sosan/backoffice-rentacarmallorca:latest
    container_name: backoffice
    ports:
      - 3100:3100
    environment:
      URL_BACKEND: backend
      URL_BACKOFFICE: backoffice
      NODE_ENV: production
    secrets:
        - PORT_BACKEND
        - PORT_BACKOFFICE
    networks:
      - gateway
    depends_on:
      - backend
  backend:
    restart: always
    image: sosan/backend-rentacarmallorca:latest
    container_name: backend
    ports:
      - 3000:3000
    networks:
      - gateway
    secrets:
      - PORT_FRONTEND
      - PORT_BACKEND
      - REDISDB_PORT
      - REDISDB_HOST
      - REDISDB_PASSWORD
      - ENDPOINT_VARIABLES_FRONTEND
      - TOKEN_FOR_BACKEND_ACCESS
    environment:
      URL_BACKEND: backend
      URL_FRONTEND: frontend
      URL_BACKOFFICE: backoffice
      NODE_ENV: production
networks:
  gateway: {}
secrets:
  REDISDB_PASSWORD:
    file: "./secrets/redisdb_password.txt"
  REDISDB_PORT:
    file: "./secrets/redisdb_port.txt"
  REDISDB_HOST:
    file: "./secrets/redisdb_host.txt"
  PORT_FRONTEND:
    file: "./secrets/port_frontend.txt"
  PORT_BACKEND:
    file: "./secrets/port_backend.txt"
  ENDPOINT_VARIABLES_FRONTEND:
    file: "./secrets/endpoint_variables_frontend.txt"
  TOKEN_FOR_BACKEND_ACCESS:
    file: "./secrets/token_for_backend_access.txt"
  PORT_BACKOFFICE:
    file: "./secrets/port_backoffice.txt"
