version: "3.8"
services:
#   frontend:
#     restart: always
#     image: sosan/frontend:v1
#     container_name: frontend
#     ports:
#       - 80:8080
#     links:
#       - backend:backend
#     environment:
#       URL_BACKEND: backend
#       URL_FRONTEND: frontend
#       NODE_ENV: production
#       PORT_FRONTEND: /run/secrets/port_frontend
#       PORT_BACKEND: /run/secrets/port_backend
#       ENDPOINT_VARIABLES_FRONTEND: /run/secrets/endpoint_variables_frontend
#     depends_on:
#       - backend
  backend:
    restart: always
    image: backend:latest
    # build:
    #   context: "."
    #   dockerfile: "Dockerfile"
    container_name: backend
    ports:
      - 3000:3000
    secrets:
      - PORT_FRONTEND
      - PORT_BACKEND
      - REDISDB_PORT
      - REDISDB_HOST
      - REDISDB_PASSWORD
      - ENDPOINT_VARIABLES_FRONTEND
    environment:
      URL_BACKEND: backend
      URL_FRONTEND: frontend
      NODE_ENV: production
secrets:
  REDISDB_PASSWORD:
    file: "./secrets/redisdb_password.txt"
  REDISDB_PORT:
    file: "./secrets/redisdb_port.txt"
  REDISDB_HOST:
    file: "./secrets/redisdb_host.txt"
  PORT_FRONTEND:
    file: "./secrets/port_frontend.txt"
  PORT_BACKEND:
    file: "./secrets/port_backend.txt"
  ENDPOINT_VARIABLES_FRONTEND:
    file: "./secrets/endpoint_variables_frontend.txt"
