name: accion para subir imagen a servidor

on:
  push:
    branches: [ backend ]
    tags:
      - 'v*'

# on:
#   push:
#     branches: [ backend ]
#   pull_request:
#     branches: [ backend ]

jobs:
  buildx:
    runs-on: ubuntu-latest
    # if: "contains(github.event.head_commit.message, 'subir')"
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: sosan/backend-rentacarmallorca:latest
          secrets: |
            "PORT_BACKEND=${{ secrets.PORT_BACKEND }}"
            "PORT_FRONTEND=${{ secrets.PORT_FRONTEND }}"
            "REDISDB_PORT=${{ secrets.REDISDB_PORT }}"
            "REDISDB_HOST=${{ secrets.REDISDB_HOST }}"
            "REDISDB_PASSWORD=${{ secrets.REDISDB_PASSWORD }}"
            "ENDPOINT_VARIABLES_FRONTEND=${{ secrets.ENDPOINT_VARIABLES_FRONTEND }}"
      
      - name: Execute SSH commmands on remote server
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: ${{ secrets.HOST_SERVIDOR }} # root@ip
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
          command: |
            ls -lah
            echo "I am $NAME"
