name: nginx
on:
  push:
    branches: [ nginx ]
jobs:
  build_nginx:
    runs-on: ubuntu-20.04
    if: "contains(github.event.head_commit.message, '/a')"
    steps:
      - name: Avoid redudant builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Get current date
        id: date
        run: echo ::set-output name=DATE_NOW::$(date +'%Y_%m_%dT%H_%M_%S')
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: Dockerfile
          platforms: linux/amd64
          push: true
          build-args: |
            EMAIL_CERTIFICATION=${{ secrets.EMAIL_CERTIFICATION }}
            DOMAIN_1=${{ secrets.DOMAIN_1 }}
            DOMAIN_2=${{ secrets.DOMAIN_2 }}
          tags: | 
            sosan/envoy-rentacarmallorca:${{steps.date.outputs.DATE_NOW}}
            sosan/envoy-rentacarmallorca:latest
          # secrets: |
          #   "SERVER_KEY_SSL=${{ secrets.SERVER_KEY_SSL }}"
          #   "SERVER_CRT_SSL=${{ secrets.SERVER_CRT_SSL }}"
          #   "SERVER_LOCAL_KEY_SSL=${{ secrets.SERVER_LOCAL_KEY_SSL }}"
          #   "SERVER_LOCAL_CRT_SSL=${{ secrets.SERVER_LOCAL_CRT_SSL }}"

      - name: Comandos SSH Servidor
        if: "contains(github.event.head_commit.message, '/b')"
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_SERVIDOR }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY}}
          port:  ${{ secrets.PORT_SERVIDOR }}
          script: |
            export DOCKER_HOST=unix://$XDG_RUNTIME_DIR/docker.sock && \
            /home/alvaro/bin/docker pull sosan/envoy-rentacarmallorca:latest

